### ISSUE TITLE
Add link to logo?

### ISSUE THREAD

**Issue by owasow** [gadenbuie/xaringan-logo#1]
Thanks so much for this logo repo and blog post and all the other work you've done to make Xaringan more accessible. I've posted most of my course slides to a distill generated site (see: http://pol346.com -> Slides 1-6 ) and have one minor issue which is that there is no simple way to navigate from the slides back to the main page (hitting the browser back button works, though). I thought of adding a small logo with homepage link to the slides as a possible solution but am uncertain if a background image can be made clickable. Might it be possible to use your logo solution for navigation? Again, many thanks for all you do!

**Comment by gadenbuie** [comment]
Thanks! Yes, this is definitely possible, in particular because the logo I add in this template repo isn't actually in the background, it's just pushed out of the way.

You just have to edit the HTML (in JavaScript) right here

https://github.com/gadenbuie/xaringan-logo/blob/c856909c5052f030871b3fedd9e4b10fb4330208/insert-logo.html#L24-L26

and replace it with something like

```js
el.innerHTML += '<a href="http://pol346.com/" class="logo"></a>';
```

**Comment by owasow** [comment]
Awesome! That worked like a charm. Much obliged!
